-- Snowflake prod DDL (same grain as Postgres local)
-- Warehouse: LEAKAGE_WH | Database: LEAKAGE_DB | Schema: MART

CREATE SCHEMA IF NOT EXISTS MART;

CREATE TABLE IF NOT EXISTS MART.DIM_COURIER (
  COURIER_ID   NUMBER PRIMARY KEY,
  COURIER_NAME VARCHAR NOT NULL UNIQUE,
  BASE_RATE_RS NUMBER(10,2) NOT NULL,
  SLA_HOURS    NUMBER NOT NULL
);

CREATE TABLE IF NOT EXISTS MART.DIM_GEOGRAPHY (
  GEO_ID NUMBER PRIMARY KEY,
  CITY   VARCHAR NOT NULL,
  TIER   VARCHAR NOT NULL,
  ZONE   VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS MART.DIM_MERCHANT (
  MERCHANT_ID   VARCHAR PRIMARY KEY,
  MERCHANT_NAME VARCHAR NOT NULL,
  CATEGORY      VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS MART.DIM_DATE (
  DATE_ID     DATE PRIMARY KEY,
  WEEK_ID     VARCHAR NOT NULL,
  MONTH_ID    VARCHAR NOT NULL,
  IS_FESTIVAL BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS MART.FACT_ORDERS (
  ORDER_ID         VARCHAR PRIMARY KEY,
  AWB_NUMBER       VARCHAR NOT NULL UNIQUE,
  COURIER_ID       NUMBER NOT NULL REFERENCES MART.DIM_COURIER(COURIER_ID),
  MERCHANT_ID      VARCHAR NOT NULL REFERENCES MART.DIM_MERCHANT(MERCHANT_ID),
  GEO_ID           NUMBER NOT NULL REFERENCES MART.DIM_GEOGRAPHY(GEO_ID),
  ORDER_DATE       DATE NOT NULL,
  DELIVERY_DATE    DATE,
  ORDER_STATUS     VARCHAR NOT NULL,
  PAYMENT_MODE     VARCHAR NOT NULL,
  COD_AMOUNT       NUMBER(12,2) NOT NULL DEFAULT 0,
  DECLARED_WEIGHT  NUMBER(8,3) NOT NULL,
  ORDER_VALUE      NUMBER(12,2) NOT NULL,
  PROMISED_ETA_HRS NUMBER NOT NULL,
  ACTUAL_ETA_HRS   NUMBER(8,2),
  CLUSTER BY (ORDER_DATE, COURIER_ID)
);

CREATE TABLE IF NOT EXISTS MART.FACT_SETTLEMENTS (
  SETTLEMENT_ID  VARCHAR PRIMARY KEY,
  AWB_NUMBER     VARCHAR NOT NULL,
  BATCH_ID       VARCHAR NOT NULL,
  COURIER_ID     NUMBER NOT NULL REFERENCES MART.DIM_COURIER(COURIER_ID),
  SETTLEMENT_DATE DATE NOT NULL,
  SETTLED_COD    NUMBER(12,2) NOT NULL DEFAULT 0,
  CHARGED_WEIGHT NUMBER(8,3) NOT NULL,
  FORWARD_CHARGE NUMBER(10,2) NOT NULL DEFAULT 0,
  RTO_CHARGE     NUMBER(10,2) NOT NULL DEFAULT 0,
  COD_FEE        NUMBER(10,2) NOT NULL DEFAULT 0,
  CLUSTER BY (SETTLEMENT_DATE, COURIER_ID)
);

CREATE TABLE IF NOT EXISTS MART.FACT_DISCREPANCIES (
  DISCREPANCY_ID   VARCHAR PRIMARY KEY,
  AWB_NUMBER       VARCHAR NOT NULL,
  BATCH_ID         VARCHAR NOT NULL,
  COURIER_ID       NUMBER NOT NULL REFERENCES MART.DIM_COURIER(COURIER_ID),
  MERCHANT_ID      VARCHAR NOT NULL REFERENCES MART.DIM_MERCHANT(MERCHANT_ID),
  GEO_ID           NUMBER NOT NULL REFERENCES MART.DIM_GEOGRAPHY(GEO_ID),
  DISCREPANCY_TYPE VARCHAR NOT NULL,
  EXPECTED_VALUE   NUMBER(12,2),
  ACTUAL_VALUE     NUMBER(12,2),
  VARIANCE_RS      NUMBER(12,2) NOT NULL DEFAULT 0,
  SEVERITY         VARCHAR NOT NULL DEFAULT 'MEDIUM',
  DETECTED_AT      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  CLUSTER BY (DISCREPANCY_TYPE, COURIER_ID)
);

CREATE TABLE IF NOT EXISTS MART.FCT_DAILY_KPIS (
  KPI_DATE      DATE NOT NULL,
  COURIER_ID    NUMBER NOT NULL,
  GEO_ID        NUMBER NOT NULL,
  ORDERS        NUMBER NOT NULL DEFAULT 0,
  DISPUTED_AWBS NUMBER NOT NULL DEFAULT 0,
  LEAKAGE_RS    NUMBER(14,2) NOT NULL DEFAULT 0,
  AVG_DSO_DAYS  NUMBER(8,2),
  PRIMARY KEY (KPI_DATE, COURIER_ID, GEO_ID)
);
